### ISSUE TITLE
Null object reference on Start

### ISSUE THREAD

**Issue by mirkoemirbc** [39499740/recorder_wav#4]
When call `startRecording()`  on console shows the follow error and cancel:
```
I/System.out( 3454): 开始录制
E/AndroidRuntime( 3454): FATAL EXCEPTION: Thread-4
E/AndroidRuntime( 3454): Process: com.mysystem.apps.myapp, PID: 3454
E/AndroidRuntime( 3454): java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.OutputStream.write(byte[])' on a null object reference
E/AndroidRuntime( 3454): 	at com.bilibili502.recorderwav.AudioUtil.writeData(AudioUtil.java:100)
E/AndroidRuntime( 3454): 	at com.bilibili502.recorderwav.AudioUtil$WriteThread.run(AudioUtil.java:68)
E/AndroidRuntime( 3454): 	at java.lang.Thread.run(Thread.java:761)
```
Is there any workaround for this?

**Comment by TimeCyber** [comment]
i have same problem
